import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/providers/theme-provider";
import { ProgressProvider } from "@/providers/progress-provider";
import { Toaster } from "@/components/ui/sonner";
import { SwrConfigProvider } from "@/providers/swr-config-provider";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Next.js Full Stack Starter Kit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className} suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" enableSystem disableTransitionOnChange>
          <ProgressProvider>
            <SwrConfigProvider>{children}</SwrConfigProvider>
          </ProgressProvider>
          <Toaster richColors />
        </ThemeProvider>
      </body>
    </html>
  );
}
